apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.uniix.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: uniix
      app.kubernetes.io/name: {{ .Release.Name }}
  replicas: {{ .Values.uniix.replicas }}
  template:
    metadata:
      labels:
        app: uniix
        app.kubernetes.io/name: {{ .Release.Name }}
    spec:
      containers:
      - name: uniix
        image: {{ .Values.uniix.image }}
        ports:
        - containerPort: 80